export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import './globals.css'

export default function RootLayout({ children }) {
 return (
    <html lang="en" data-theme="light">
      <body className="p-5">{children}</body>
    </html>
  )
}
